

import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { ThemeProvider } from "next-themes"; // new
import "./globals.css";
import AuthInit from "@/component/Provider/AuthInit";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={poppins.variable}>
      <body>
        {/* ThemeProvider wraps the app */}
        <ThemeProvider attribute="class" defaultTheme="system">
          <AuthInit />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
